version: '2.0'
services:
  # rasa:
  #   image: rasa-abl:v1
  #   # ports:
  #   #   - 5005:5005
  #   volumes:
  #     - ./:/app
  #   command:
  #     - run
  #     - -m
  #     - models
  #     - --enable-api
  #     - --cors
  #     - "*"
  # nginx:
  #   image: nginx:latest
  #   volumes: 
  #     - ./conf.d:/etc/nginx/conf.d
  #   depends_on:
  #     - rasa
     
    # ports:
    #   - 3000:3000
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
